score_board = {
  "results": {
    "2022-01-01": [],
    "2022-01-02": {
      "data": {
        "1411596": {
          "stadium": "Nissan Stadium",
          "event_id": "1411596",
          "event_date": "2022-01-02 13:00",
          "home_team_id": "62",
          "home_primary_color": "#00295B",
          "home_secondary_color": "#347AAA",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "TEN",
          "home_name": "Tennessee Titans",
          "home_nick_name": "Titans",
          "home_city": "Tennessee",
          "home_image_id": "",
          "away_team_id": "65",
          "away_primary_color": "#006666",
          "away_secondary_color": "#DF6108",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "MIA",
          "away_name": "Miami Dolphins",
          "away_nick_name": "Dolphins",
          "away_city": "Miami",
          "away_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "3",
          "home_score": "34",
          "boxscore_available": "Yes",
          "home_short_name": "TEN",
          "away_short_name": "MIA",
          "home_display_name": "Tennessee",
          "away_display_name": "Miami",
          "tv_station": "CBS",
          "tv_station_name": "CBS",
          "surface": "Grass",
          "stadium_rotation": "155",
          "roof": "Open",
          "away_record": "8-7",
          "home_record": "10-5",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "H": {
                "quarter1score": "7",
                "quarter2score": "10",
                "quarter3score": "0",
                "quarter4score": "17",
                "overtimescore": "0",
                "totalscore": "34"
              },
              "A": {
                "quarter1score": "0",
                "quarter2score": "3",
                "quarter3score": "0",
                "quarter4score": "0",
                "overtimescore": "0",
                "totalscore": "3"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "120",
          "away_rotation": "119"
        },
        "1411601": {
          "stadium": "Soldier Field",
          "event_id": "1411601",
          "event_date": "2022-01-02 13:00",
          "home_team_id": "43",
          "home_primary_color": "#091F3D",
          "home_secondary_color": "#EC6E24",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "CHI",
          "home_name": "Chicago Bears",
          "home_nick_name": "Bears",
          "home_city": "Chicago",
          "home_image_id": "",
          "away_team_id": "55",
          "away_primary_color": "#003B7D",
          "away_secondary_color": "#808080",
          "away_tertiary_color": "#CA233D",
          "away_abbreviation": "NYG",
          "away_name": "New York Giants",
          "away_nick_name": "Giants",
          "away_city": "New York",
          "away_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "3",
          "home_score": "29",
          "boxscore_available": "Yes",
          "home_short_name": "CHI",
          "away_short_name": "NYG",
          "home_display_name": "Chicago",
          "away_display_name": "New York",
          "tv_station": "CBS",
          "tv_station_name": "CBS",
          "surface": "Grass",
          "stadium_rotation": "175",
          "roof": "Open",
          "away_record": "4-11",
          "home_record": "5-10",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "H": {
                "quarter1score": "14",
                "quarter2score": "8",
                "quarter3score": "7",
                "quarter4score": "0",
                "overtimescore": "0",
                "totalscore": "29"
              },
              "A": {
                "quarter1score": "0",
                "quarter2score": "3",
                "quarter3score": "0",
                "quarter4score": "0",
                "overtimescore": "0",
                "totalscore": "3"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "104",
          "away_rotation": "103"
        },
        "1411611": {
          "stadium": "Paul Brown Stadium",
          "event_id": "1411611",
          "event_date": "2022-01-02 13:00",
          "home_team_id": "41",
          "home_primary_color": "#000000",
          "home_secondary_color": "#FB4F14",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "CIN",
          "home_name": "Cincinnati Bengals",
          "home_nick_name": "Bengals",
          "home_city": "Cincinnati",
          "home_image_id": "",
          "away_team_id": "63",
          "away_primary_color": "#E1AC00",
          "away_secondary_color": "#BD0100",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "KC",
          "away_name": "Kansas City Chiefs",
          "away_nick_name": "Chiefs",
          "away_city": "Kansas City",
          "away_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "31",
          "home_score": "34",
          "boxscore_available": "Yes",
          "home_short_name": "CIN",
          "away_short_name": "KC",
          "home_display_name": "Cincinnati",
          "away_display_name": "Kansas City",
          "tv_station": "CBS",
          "tv_station_name": "CBS",
          "surface": "Turf",
          "stadium_rotation": "140",
          "roof": "Open",
          "away_record": "11-4",
          "home_record": "9-6",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "H": {
                "quarter1score": "7",
                "quarter2score": "10",
                "quarter3score": "7",
                "quarter4score": "10",
                "overtimescore": "0",
                "totalscore": "34"
              },
              "A": {
                "quarter1score": "14",
                "quarter2score": "14",
                "quarter3score": "0",
                "quarter4score": "3",
                "overtimescore": "0",
                "totalscore": "31"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "116",
          "away_rotation": "115"
        },
        "1411616": {
          "stadium": "FedEx Field",
          "event_id": "1411616",
          "event_date": "2022-01-02 13:00",
          "away_team_id": "40",
          "away_primary_color": "#034B57",
          "away_secondary_color": "#7A7D80",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "PHI",
          "away_name": "Philadelphia Eagles",
          "away_nick_name": "Eagles",
          "away_city": "Philadelphia",
          "away_image_id": "",
          "home_team_id": "51",
          "home_primary_color": "#E1AC00",
          "home_secondary_color": "#691B11",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "WAS",
          "home_name": "Washington Football Team",
          "home_nick_name": "Football Team",
          "home_city": "Washington",
          "home_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "20",
          "home_score": "16",
          "boxscore_available": "Yes",
          "home_short_name": "WAS",
          "away_short_name": "PHI",
          "home_display_name": "Washington",
          "away_display_name": "Philadelphia",
          "tv_station": "FOX",
          "tv_station_name": "FOX",
          "surface": "Grass",
          "stadium_rotation": "120",
          "roof": "Open",
          "away_record": "8-7",
          "home_record": "6-9",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "A": {
                "quarter1score": "0",
                "quarter2score": "7",
                "quarter3score": "7",
                "quarter4score": "6",
                "overtimescore": "0",
                "totalscore": "20"
              },
              "H": {
                "quarter1score": "10",
                "quarter2score": "6",
                "quarter3score": "0",
                "quarter4score": "0",
                "overtimescore": "0",
                "totalscore": "16"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "114",
          "away_rotation": "113"
        },
        "1411621": {
          "stadium": "MetLife Stadium",
          "event_id": "1411621",
          "event_date": "2022-01-02 13:00",
          "home_team_id": "54",
          "home_primary_color": "#055032",
          "home_secondary_color": "#055032",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "NYJ",
          "home_name": "New York Jets",
          "home_nick_name": "Jets",
          "home_city": "New York",
          "home_image_id": "",
          "away_team_id": "68",
          "away_primary_color": "#706051",
          "away_secondary_color": "#BD152C",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "TB",
          "away_name": "Tampa Bay Buccaneers",
          "away_nick_name": "Buccaneers",
          "away_city": "Tampa Bay",
          "away_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "28",
          "home_score": "24",
          "boxscore_available": "Yes",
          "home_short_name": "NYJ",
          "away_short_name": "TB",
          "home_display_name": "New York",
          "away_display_name": "Tampa Bay",
          "tv_station": "FOX",
          "tv_station_name": "FOX",
          "surface": "Turf",
          "stadium_rotation": "170",
          "roof": "Open",
          "away_record": "11-4",
          "home_record": "4-11",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "H": {
                "quarter1score": "7",
                "quarter2score": "10",
                "quarter3score": "7",
                "quarter4score": "0",
                "overtimescore": "0",
                "totalscore": "24"
              },
              "A": {
                "quarter1score": "7",
                "quarter2score": "3",
                "quarter3score": "7",
                "quarter4score": "11",
                "overtimescore": "0",
                "totalscore": "28"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "106",
          "away_rotation": "105"
        },
        "1411626": {
          "stadium": "Gillette Stadium",
          "event_id": "1411626",
          "event_date": "2022-01-02 13:00",
          "home_team_id": "44",
          "home_primary_color": "#03275B",
          "home_secondary_color": "#888685",
          "home_tertiary_color": "#D02F27",
          "home_abbreviation": "NE",
          "home_name": "New England Patriots",
          "home_nick_name": "Patriots",
          "home_city": "New England",
          "home_image_id": "",
          "away_team_id": "69",
          "away_primary_color": "#000000",
          "away_secondary_color": "#007197",
          "away_tertiary_color": "#CEB139",
          "away_abbreviation": "JAC",
          "away_name": "Jacksonville Jaguars",
          "away_nick_name": "Jaguars",
          "away_city": "Jacksonville",
          "away_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "10",
          "home_score": "50",
          "boxscore_available": "Yes",
          "home_short_name": "NE",
          "away_short_name": "JAC",
          "home_display_name": "New England",
          "away_display_name": "Jacksonville",
          "tv_station": "CBS",
          "tv_station_name": "CBS",
          "surface": "Turf",
          "stadium_rotation": "165",
          "roof": "Open",
          "away_record": "2-13",
          "home_record": "9-6",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "H": {
                "quarter1score": "7",
                "quarter2score": "21",
                "quarter3score": "13",
                "quarter4score": "9",
                "overtimescore": "0",
                "totalscore": "50"
              },
              "A": {
                "quarter1score": "3",
                "quarter2score": "0",
                "quarter3score": "0",
                "quarter4score": "7",
                "overtimescore": "0",
                "totalscore": "10"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "118",
          "away_rotation": "117"
        },
        "1411631": {
          "stadium": "Lucas Oil Stadium",
          "event_id": "1411631",
          "event_date": "2022-01-02 13:00",
          "away_team_id": "66",
          "away_primary_color": "#000000",
          "away_secondary_color": "#7A7D80",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "LV",
          "away_name": "Las Vegas Raiders",
          "away_nick_name": "Raiders",
          "away_city": "Las Vegas",
          "away_image_id": "",
          "home_team_id": "67",
          "home_primary_color": "#003B7B",
          "home_secondary_color": "#003B7B",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "IND",
          "home_name": "Indianapolis Colts",
          "home_nick_name": "Colts",
          "home_city": "Indianapolis",
          "home_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "23",
          "home_score": "20",
          "boxscore_available": "Yes",
          "home_short_name": "IND",
          "away_short_name": "LV",
          "home_display_name": "Indianapolis",
          "away_display_name": "Las Vegas",
          "tv_station": "CBS",
          "tv_station_name": "CBS",
          "surface": "Turf",
          "stadium_rotation": "25",
          "roof": "Retractable",
          "away_record": "8-7",
          "home_record": "9-6",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "A": {
                "quarter1score": "7",
                "quarter2score": "6",
                "quarter3score": "0",
                "quarter4score": "10",
                "overtimescore": "0",
                "totalscore": "23"
              },
              "H": {
                "quarter1score": "0",
                "quarter2score": "10",
                "quarter3score": "7",
                "quarter4score": "3",
                "overtimescore": "0",
                "totalscore": "20"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "102",
          "away_rotation": "101"
        },
        "1411636": {
          "stadium": "Highmark Stadium",
          "event_id": "1411636",
          "event_date": "2022-01-02 13:00",
          "away_team_id": "49",
          "away_primary_color": "#000000",
          "away_secondary_color": "#BD0D18",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "ATL",
          "away_name": "Atlanta Falcons",
          "away_nick_name": "Falcons",
          "away_city": "Atlanta",
          "away_image_id": "",
          "home_team_id": "53",
          "home_primary_color": "#005596",
          "home_secondary_color": "#DA2128",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "BUF",
          "home_name": "Buffalo Bills",
          "home_nick_name": "Bills",
          "home_city": "Buffalo",
          "home_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "15",
          "home_score": "29",
          "boxscore_available": "Yes",
          "home_short_name": "BUF",
          "away_short_name": "ATL",
          "home_display_name": "Buffalo",
          "away_display_name": "Atlanta",
          "tv_station": "FOX",
          "tv_station_name": "FOX",
          "surface": "Turf",
          "stadium_rotation": "120",
          "roof": "Open",
          "away_record": "7-8",
          "home_record": "9-6",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "A": {
                "quarter1score": "2",
                "quarter2score": "13",
                "quarter3score": "0",
                "quarter4score": "0",
                "overtimescore": "0",
                "totalscore": "15"
              },
              "H": {
                "quarter1score": "14",
                "quarter2score": "0",
                "quarter3score": "8",
                "quarter4score": "7",
                "overtimescore": "0",
                "totalscore": "29"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "108",
          "away_rotation": "107"
        },
        "1411656": {
          "stadium": "M&T Bank Stadium",
          "event_id": "1411656",
          "event_date": "2022-01-02 13:00",
          "home_team_id": "48",
          "home_primary_color": "#000000",
          "home_secondary_color": "#2C2E81",
          "home_tertiary_color": "#DEAC33",
          "home_abbreviation": "BAL",
          "home_name": "Baltimore Ravens",
          "home_nick_name": "Ravens",
          "home_city": "Baltimore",
          "home_image_id": "",
          "away_team_id": "64",
          "away_primary_color": "#13264B",
          "away_secondary_color": "#BE9B4B",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "LAR",
          "away_name": "Los Angeles Rams",
          "away_nick_name": "Rams",
          "away_city": "Los Angeles",
          "away_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "20",
          "home_score": "19",
          "boxscore_available": "Yes",
          "home_short_name": "BAL",
          "away_short_name": "LAR",
          "home_display_name": "Baltimore",
          "away_display_name": "Los Angeles",
          "tv_station": "FOX",
          "tv_station_name": "FOX",
          "surface": "Grass",
          "stadium_rotation": "110",
          "roof": "Open",
          "away_record": "11-4",
          "home_record": "8-7",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "H": {
                "quarter1score": "7",
                "quarter2score": "6",
                "quarter3score": "3",
                "quarter4score": "3",
                "overtimescore": "0",
                "totalscore": "19"
              },
              "A": {
                "quarter1score": "0",
                "quarter2score": "7",
                "quarter3score": "0",
                "quarter4score": "13",
                "overtimescore": "0",
                "totalscore": "20"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "128",
          "away_rotation": "127"
        },
        "1411641": {
          "stadium": "Levi's Stadium",
          "event_id": "1411641",
          "event_date": "2022-01-02 16:05",
          "away_team_id": "42",
          "away_primary_color": "#02253A",
          "away_secondary_color": "#B31B34",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "HOU",
          "away_name": "Houston Texans",
          "away_nick_name": "Texans",
          "away_city": "Houston",
          "away_image_id": "",
          "home_team_id": "58",
          "home_primary_color": "#AB8B54",
          "home_secondary_color": "#AA000A",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "SF",
          "home_name": "San Francisco 49ers",
          "home_nick_name": "49ers",
          "home_city": "San Francisco",
          "home_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "7",
          "home_score": "23",
          "boxscore_available": "Yes",
          "home_short_name": "SF",
          "away_short_name": "HOU",
          "home_display_name": "San Francisco",
          "away_display_name": "Houston",
          "tv_station": "CBS",
          "tv_station_name": "CBS",
          "surface": "Grass",
          "stadium_rotation": "150",
          "roof": "Open",
          "away_record": "4-11",
          "home_record": "8-7",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "A": {
                "quarter1score": "0",
                "quarter2score": "7",
                "quarter3score": "0",
                "quarter4score": "0",
                "overtimescore": "0",
                "totalscore": "7"
              },
              "H": {
                "quarter1score": "0",
                "quarter2score": "3",
                "quarter3score": "7",
                "quarter4score": "13",
                "overtimescore": "0",
                "totalscore": "23"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "124",
          "away_rotation": "123"
        },
        "1411646": {
          "stadium": "SoFi Stadium",
          "event_id": "1411646",
          "event_date": "2022-01-02 16:05",
          "home_team_id": "47",
          "home_primary_color": "#002859",
          "home_secondary_color": "#3477B8",
          "home_tertiary_color": "#FFC30D",
          "home_abbreviation": "LAC",
          "home_name": "Los Angeles Chargers",
          "home_nick_name": "Chargers",
          "home_city": "Los Angeles",
          "home_image_id": "",
          "away_team_id": "61",
          "away_primary_color": "#002244",
          "away_secondary_color": "#FB4F14",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "DEN",
          "away_name": "Denver Broncos",
          "away_nick_name": "Broncos",
          "away_city": "Denver",
          "away_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "13",
          "home_score": "34",
          "boxscore_available": "Yes",
          "home_short_name": "LAC",
          "away_short_name": "DEN",
          "home_display_name": "Los Angeles",
          "away_display_name": "Denver",
          "tv_station": "CBS",
          "tv_station_name": "CBS",
          "away_record": "7-8",
          "home_record": "8-7",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "H": {
                "quarter1score": "7",
                "quarter2score": "10",
                "quarter3score": "3",
                "quarter4score": "14",
                "overtimescore": "0",
                "totalscore": "34"
              },
              "A": {
                "quarter1score": "0",
                "quarter2score": "3",
                "quarter3score": "0",
                "quarter4score": "10",
                "overtimescore": "0",
                "totalscore": "13"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "122",
          "away_rotation": "121",
          "stadium_rotation": "",
          "roof": "",
          "surface": ""
        },
        "1411591": {
          "stadium": "Caesars Superdome",
          "event_id": "1411591",
          "event_date": "2022-01-02 16:25",
          "away_team_id": "59",
          "away_primary_color": "#089DC5",
          "away_secondary_color": "#888F92",
          "away_tertiary_color": "#000000",
          "away_abbreviation": "CAR",
          "away_name": "Carolina Panthers",
          "away_nick_name": "Panthers",
          "away_city": "Carolina",
          "away_image_id": "",
          "home_team_id": "70",
          "home_primary_color": "#000000",
          "home_secondary_color": "#AB8B54",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "NO",
          "home_name": "New Orleans Saints",
          "home_nick_name": "Saints",
          "home_city": "New Orleans",
          "home_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "10",
          "home_score": "18",
          "boxscore_available": "Yes",
          "home_short_name": "NO",
          "away_short_name": "CAR",
          "home_display_name": "New Orleans",
          "away_display_name": "Carolina",
          "tv_station": "FOX",
          "tv_station_name": "FOX",
          "surface": "Turf",
          "stadium_rotation": "90",
          "roof": "Indoor",
          "away_record": "5-10",
          "home_record": "7-8",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "A": {
                "quarter1score": "3",
                "quarter2score": "7",
                "quarter3score": "0",
                "quarter4score": "0",
                "overtimescore": "0",
                "totalscore": "10"
              },
              "H": {
                "quarter1score": "3",
                "quarter2score": "6",
                "quarter3score": "3",
                "quarter4score": "6",
                "overtimescore": "0",
                "totalscore": "18"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "112",
          "away_rotation": "111"
        },
        "1411606": {
          "stadium": "AT&T Stadium",
          "event_id": "1411606",
          "event_date": "2022-01-02 16:25",
          "away_team_id": "45",
          "away_primary_color": "#000000",
          "away_secondary_color": "#870619",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "ARI",
          "away_name": "Arizona Cardinals",
          "away_nick_name": "Cardinals",
          "away_city": "Arizona",
          "away_image_id": "",
          "home_team_id": "56",
          "home_primary_color": "#002244",
          "home_secondary_color": "#8C8B8A",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "DAL",
          "home_name": "Dallas Cowboys",
          "home_nick_name": "Cowboys",
          "home_city": "Dallas",
          "home_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "25",
          "home_score": "22",
          "boxscore_available": "Yes",
          "home_short_name": "DAL",
          "away_short_name": "ARI",
          "home_display_name": "Dallas",
          "away_display_name": "Arizona",
          "tv_station": "FOX",
          "tv_station_name": "FOX",
          "surface": "Turf",
          "stadium_rotation": "20",
          "roof": "Retractable",
          "away_record": "10-5",
          "home_record": "11-4",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "A": {
                "quarter1score": "3",
                "quarter2score": "10",
                "quarter3score": "9",
                "quarter4score": "3",
                "overtimescore": "0",
                "totalscore": "25"
              },
              "H": {
                "quarter1score": "0",
                "quarter2score": "7",
                "quarter3score": "0",
                "quarter4score": "15",
                "overtimescore": "0",
                "totalscore": "22"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "110",
          "away_rotation": "109"
        },
        "1411651": {
          "stadium": "Lumen Field",
          "event_id": "1411651",
          "event_date": "2022-01-02 16:25",
          "away_team_id": "50",
          "away_primary_color": "#006DB0",
          "away_secondary_color": "#7F818A",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "DET",
          "away_name": "Detroit Lions",
          "away_nick_name": "Lions",
          "away_city": "Detroit",
          "away_image_id": "",
          "home_team_id": "52",
          "home_primary_color": "#0B2343",
          "home_secondary_color": "#549F27",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "SEA",
          "home_name": "Seattle Seahawks",
          "home_nick_name": "Seahawks",
          "home_city": "Seattle",
          "home_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "29",
          "home_score": "51",
          "boxscore_available": "Yes",
          "home_short_name": "SEA",
          "away_short_name": "DET",
          "home_display_name": "Seattle",
          "away_display_name": "Detroit",
          "tv_station": "FOX",
          "tv_station_name": "FOX",
          "surface": "Turf",
          "stadium_rotation": "0",
          "roof": "Open",
          "away_record": "2-12-1",
          "home_record": "5-10",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "A": {
                "quarter1score": "0",
                "quarter2score": "7",
                "quarter3score": "15",
                "quarter4score": "7",
                "overtimescore": "0",
                "totalscore": "29"
              },
              "H": {
                "quarter1score": "10",
                "quarter2score": "21",
                "quarter3score": "7",
                "quarter4score": "13",
                "overtimescore": "0",
                "totalscore": "51"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "126",
          "away_rotation": "125"
        },
        "1411661": {
          "stadium": "Lambeau Field",
          "event_id": "1411661",
          "event_date": "2022-01-02 20:20",
          "home_team_id": "39",
          "home_primary_color": "#244729",
          "home_secondary_color": "#E0A200",
          "home_tertiary_color": "#FFFFFF",
          "home_abbreviation": "GB",
          "home_name": "Green Bay Packers",
          "home_nick_name": "Packers",
          "home_city": "Green Bay",
          "home_image_id": "",
          "away_team_id": "57",
          "away_primary_color": "#3B0160",
          "away_secondary_color": "#CE9D00",
          "away_tertiary_color": "#FFFFFF",
          "away_abbreviation": "MIN",
          "away_name": "Minnesota Vikings",
          "away_nick_name": "Vikings",
          "away_city": "Minnesota",
          "away_image_id": "",
          "event_status": "Complete",
          "status": "Final",
          "away_score": "10",
          "home_score": "37",
          "boxscore_available": "Yes",
          "home_short_name": "GB",
          "away_short_name": "MIN",
          "home_display_name": "Green Bay",
          "away_display_name": "Minnesota",
          "tv_station": "NBC",
          "tv_station_name": "NBC",
          "surface": "Grass",
          "stadium_rotation": "180",
          "roof": "Open",
          "away_record": "7-8",
          "home_record": "12-3",
          "recap_available": "Yes",
          "scoring": {
            "data": {
              "H": {
                "quarter1score": "3",
                "quarter2score": "17",
                "quarter3score": "10",
                "quarter4score": "7",
                "overtimescore": "0",
                "totalscore": "37"
              },
              "A": {
                "quarter1score": "0",
                "quarter2score": "3",
                "quarter3score": "7",
                "quarter4score": "0",
                "overtimescore": "0",
                "totalscore": "10"
              }
            },
            "columns": {
              "quarter1score": "Quarter1Score",
              "quarter2score": "Quarter2Score",
              "quarter3score": "Quarter3Score",
              "quarter4score": "Quarter4Score",
              "overtimescore": "OvertimeScore",
              "totalscore": "TotalScore"
            }
          },
          "home_rotation": "130",
          "away_rotation": "129"
        }
      },
      "columns": {
        "away_record": "away record",
        "home_record": "home record",
        "event_id": "event id",
        "event_date": "event date",
        "away_team_id": "away team id",
        "away_abbreviation": "away abbreviation",
        "away_name": "away name",
        "away_city": "away city",
        "away_nick_name": "away nick name",
        "away_image_id": "away image id",
        "away_primary_color": "Away Primary Color",
        "away_secondary_color": "Away Secondary Color",
        "away_tertiary_color": "Away Tertiary Color",
        "home_team_id": "home team id",
        "home_name": "home name",
        "home_city": "home city",
        "home_nick_name": "home nick name",
        "home_abbreviation": "home abbreviaiton",
        "home_image_id": "home image id",
        "home_primary_color": "Home Primary Color",
        "home_secondary_color": "Home Secondary Color",
        "home_tertiary_color": "Home Tertiary Color",
        "stadium": "Stadium",
        "away_score": "away score",
        "home_score": "home score",
        "away_short_name": "Away Short Name",
        "home_short_name": "Home Short Name",
        "status": "Status",
        "recap_available": "recap available",
        "boxscore_available": "Boxscore Available",
        "scoring": "scoring",
        "home_rotation": "Home Rotation Number",
        "away_rotation": "Away Rotation Number",
        "weather_code": "Weather Code",
        "stadium_rotation": "Stadium Rotation",
        "roof": "Roof",
        "surface": "surface",
        "away_display_name": "away display name",
        "home_display_name": "home display name"
      }
    }
  },
  "hash": "50de95ab04ebb3582e61ae718bf59e56"
}

ranking = {
  "results": {
    "data": [
      {
        "team_id": "53",
        "team": "Buffalo",
        "rank": "1",
        "last_week": "1",
        "points": "45.434",
        "modifier": "0.600",
        "adjusted_points": "27.260"
      },
      {
        "team_id": "63",
        "team": "Kansas City",
        "rank": "2",
        "last_week": "2",
        "points": "26.076",
        "modifier": "0.470",
        "adjusted_points": "12.256"
      },
      {
        "team_id": "56",
        "team": "Dallas",
        "rank": "3",
        "last_week": "3",
        "points": "22.596",
        "modifier": "0.489",
        "adjusted_points": "11.047"
      },
      {
        "team_id": "41",
        "team": "Cincinnati",
        "rank": "4",
        "last_week": "5",
        "points": "19.830",
        "modifier": "0.489",
        "adjusted_points": "9.695"
      },
      {
        "team_id": "40",
        "team": "Philadelphia",
        "rank": "5",
        "last_week": "4",
        "points": "18.943",
        "modifier": "0.462",
        "adjusted_points": "8.761"
      },
      {
        "team_id": "58",
        "team": "San Francisco",
        "rank": "6",
        "last_week": "6",
        "points": "16.206",
        "modifier": "0.438",
        "adjusted_points": "7.090"
      },
      {
        "team_id": "57",
        "team": "Minnesota",
        "rank": "7",
        "last_week": "7",
        "points": "13.330",
        "modifier": "0.500",
        "adjusted_points": "6.665"
      },
      {
        "team_id": "44",
        "team": "New England",
        "rank": "8",
        "last_week": "8",
        "points": "12.273",
        "modifier": "0.467",
        "adjusted_points": "5.727"
      },
      {
        "team_id": "52",
        "team": "Seattle",
        "rank": "9",
        "last_week": "9",
        "points": "7.418",
        "modifier": "0.456",
        "adjusted_points": "3.379"
      },
      {
        "team_id": "68",
        "team": "Tampa Bay",
        "rank": "10",
        "last_week": "10",
        "points": "6.451",
        "modifier": "0.480",
        "adjusted_points": "3.097"
      },
      {
        "team_id": "48",
        "team": "Baltimore",
        "rank": "11",
        "last_week": "11",
        "points": "5.421",
        "modifier": "0.530",
        "adjusted_points": "2.873"
      },
      {
        "team_id": "65",
        "team": "Miami",
        "rank": "12",
        "last_week": "12",
        "points": "5.065",
        "modifier": "0.530",
        "adjusted_points": "2.684"
      },
      {
        "team_id": "69",
        "team": "Jacksonville",
        "rank": "13",
        "last_week": "13",
        "points": "4.704",
        "modifier": "0.489",
        "adjusted_points": "2.300"
      },
      {
        "team_id": "54",
        "team": "NY Jets",
        "rank": "14",
        "last_week": "14",
        "points": "-1.304",
        "modifier": "0.500",
        "adjusted_points": "-0.652"
      },
      {
        "team_id": "39",
        "team": "Green Bay",
        "rank": "15",
        "last_week": "15",
        "points": "-3.983",
        "modifier": "0.580",
        "adjusted_points": "-1.673"
      },
      {
        "team_id": "60",
        "team": "Cleveland",
        "rank": "16",
        "last_week": "17",
        "points": "-4.108",
        "modifier": "0.500",
        "adjusted_points": "-2.054"
      },
      {
        "team_id": "55",
        "team": "NY Giants",
        "rank": "17",
        "last_week": "18",
        "points": "-4.339",
        "modifier": "0.450",
        "adjusted_points": "-2.387"
      },
      {
        "team_id": "70",
        "team": "New Orleans",
        "rank": "18",
        "last_week": "19",
        "points": "-4.739",
        "modifier": "0.490",
        "adjusted_points": "-2.417"
      },
      {
        "team_id": "51",
        "team": "Washington",
        "rank": "19",
        "last_week": "16",
        "points": "-6.398",
        "modifier": "0.544",
        "adjusted_points": "-2.915"
      },
      {
        "team_id": "61",
        "team": "Denver",
        "rank": "20",
        "last_week": "20",
        "points": "-7.486",
        "modifier": "0.490",
        "adjusted_points": "-3.818"
      },
      {
        "team_id": "45",
        "team": "Arizona",
        "rank": "21",
        "last_week": "21",
        "points": "-8.891",
        "modifier": "0.538",
        "adjusted_points": "-4.112"
      },
      {
        "team_id": "67",
        "team": "Indianapolis",
        "rank": "22",
        "last_week": "22",
        "points": "-7.548",
        "modifier": "0.438",
        "adjusted_points": "-4.246"
      },
      {
        "team_id": "47",
        "team": "LA Chargers",
        "rank": "23",
        "last_week": "23",
        "points": "-7.430",
        "modifier": "0.422",
        "adjusted_points": "-4.293"
      },
      {
        "team_id": "62",
        "team": "Tennessee",
        "rank": "24",
        "last_week": "24",
        "points": "-9.899",
        "modifier": "0.475",
        "adjusted_points": "-5.197"
      },
      {
        "team_id": "66",
        "team": "Las Vegas",
        "rank": "25",
        "last_week": "25",
        "points": "-10.561",
        "modifier": "0.422",
        "adjusted_points": "-6.102"
      },
      {
        "team_id": "50",
        "team": "Detroit",
        "rank": "26",
        "last_week": "26",
        "points": "-16.484",
        "modifier": "0.600",
        "adjusted_points": "-6.594"
      },
      {
        "team_id": "43",
        "team": "Chicago",
        "rank": "27",
        "last_week": "27",
        "points": "-15.141",
        "modifier": "0.550",
        "adjusted_points": "-6.813"
      },
      {
        "team_id": "46",
        "team": "Pittsburgh",
        "rank": "28",
        "last_week": "28",
        "points": "-18.027",
        "modifier": "0.560",
        "adjusted_points": "-7.932"
      },
      {
        "team_id": "64",
        "team": "LA Rams",
        "rank": "29",
        "last_week": "29",
        "points": "-17.118",
        "modifier": "0.514",
        "adjusted_points": "-8.314"
      },
      {
        "team_id": "49",
        "team": "Atlanta",
        "rank": "30",
        "last_week": "30",
        "points": "-16.723",
        "modifier": "0.444",
        "adjusted_points": "-9.290"
      },
      {
        "team_id": "42",
        "team": "Houston",
        "rank": "31",
        "last_week": "31",
        "points": "-19.678",
        "modifier": "0.478",
        "adjusted_points": "-10.276"
      },
      {
        "team_id": "59",
        "team": "Carolina",
        "rank": "32",
        "last_week": "32",
        "points": "-20.837",
        "modifier": "0.456",
        "adjusted_points": "-11.345"
      }
    ],
    "columns": {
      "team_id": "Team Id",
      "team": "team_name",
      "rank": "Rank",
      "last_week": "Last Week",
      "points": "points",
      "modifier": "modifier",
      "adjusted_points": "adjusted points"
    },
    "last_update": "2022-11-15 06:18"
  },
  "hash": "56a99b463ea13c3cc64c80728a446170"
}